# Generated by Django 4.2.5 on 2023-09-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_some'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='some',
        ),
    ]
