# Generated by Django 4.2.5 on 2023-09-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_options_alter_profile_user_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
